//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shitty_Server_Stopper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shitty_Server_Stopper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0.2.7 - 2/4/18
        ///- Fixed Update Form being hidden
        ///- Fixed crashing if rule(s) already exist
        ///- Changed Update UI
        ///- Added Uninstaller
        ///- RELEASED :) 
        ///_______________________________________________________________________________
        ///v0.2.6
        ///- Fixed Blocked IPs Not Saving
        ///- Fixed Not Being Able to add custom IPs
        ///- Fixed Loading of Custom IPs
        ///- Fixed First Time Setup being ran when it&apos;s not suppose to
        ///- Changed About Form UI
        ///- Changed New Update Form UI
        ///- Added Error 6: Rule Already Exists
        ///- Removed So [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeLog {
            get {
                return ResourceManager.GetString("ChangeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 46.174.48.20,46.174.48.189,46.174.52.3,46.174.52.8,46.174.52.26,46.174.54.89,89.184.10.77,91.32.139.191,104.243.46.122,185.50.105.210,188.134.2.223,194.1.236.157,201.82.201.45,201.214.26.128,210.194.213.10,212.75.210.39,108.61.10.125,108.61.10.124,192.223.31.191,66.150.121.181,74.91.114.244,68.232.166.105,206.217.139.100,74.91.119.247,192.223.24.17,74.91.126.33,74.91.118.8,74.91.120.197,66.55.154.110,66.55.154.46,216.52.143.154,107.181.178.201,207.246.66.175,108.61.125.67,66.150.214.154,74.91.126.10,68.232. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string complete_list {
            get {
                return ResourceManager.GetString("complete_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 204.11.16.132-139.162.79.149-72.11.148.168-204.11.16.134-167.160.36.76-72.11.148.168-82.211.30.241.
        /// </summary>
        internal static string hentairape_servers {
            get {
                return ResourceManager.GetString("hentairape_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 139.162.30.4-204.11.16.135-162.217.248.223.
        /// </summary>
        internal static string lewd4dead_servers {
            get {
                return ResourceManager.GetString("lewd4dead_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 74.91.112.57-66.85.14.37-74.91.116.113-66.150.121.176-108.61.10.125-108.61.10.124-192.223.31.191-66.150.121.181-74.91.114.244-192.223.27.251-139.99.8.171-216.52.148.77-66.150.121.181-74.91.112.57-66.85.14.37:27015-74.91.120.197-66.55.154.110-66.55.154.46:27045-73.166.184.238-74.91.123.74-74.208.228.57-104.153.108.113-206.217.139.100-74.91.119.247-192.223.24.17-74.91.126.33-74.91.118.8-68.232.163.38-63.251.20.27-68.232.172.105-72.5.102.151-192.99.47.29-208.167.234.174-208.167.234.179-216.52.143.154-107.181.1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string misc_modded {
            get {
                return ResourceManager.GetString("misc_modded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] shitty_server_stopper_uninstaller {
            get {
                object obj = ResourceManager.GetObject("shitty_server_stopper_uninstaller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45.32.24.56.
        /// </summary>
        internal static string yandere_servers {
            get {
                return ResourceManager.GetString("yandere_servers", resourceCulture);
            }
        }
    }
}
